name: CI

on:
  push:
  pull_request: 
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    runs-on: ubuntu-latest
    name: NPM + Foundry build pipeline

    steps:
      # Step 1 — Checkout repository
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      # Step 2 — Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3 — Cache npm dependencies
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 4 — Install dependencies
      - name: Install NPM dependencies
        run: npm ci

      # Step 5 — Run full pipeline
      - name: Build, Compile, and Test
        run: |
          npm run build
          npm run test
