name: Publish Oracle Package

on:
  push:
    tags:
      - "v*"   # triggers when you push a version tag like v0.1.0

permissions:
  contents: read
  packages: write   # allows publishing to GitHub Packages

jobs:
  # Step 1 — Reuse your existing CI workflow (build + tests)
  test:
    uses: ./.github/workflows/ci.yml

  # Step 2 — Publish only if CI passes
  publish:
    needs: test
    runs-on: ubuntu-latest
    name: Publish to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com/"

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
